using System;

namespace SixtenLabs.SpawnOfVulkan
{
    public struct PhysicalDeviceLimits
    {
        internal uint MaxImageDimension1D;
        internal uint MaxImageDimension2D;
        internal uint MaxImageDimension3D;
        internal uint MaxImageDimensionCube;
        internal uint MaxImageArrayLayers;
        internal uint MaxTexelBufferElements;
        internal uint MaxUniformBufferRange;
        internal uint MaxStorageBufferRange;
        internal uint MaxPushConstantsSize;
        internal uint MaxMemoryAllocationCount;
        internal uint MaxSamplerAllocationCount;
        internal ulong BufferImageGranularity;
        internal ulong SparseAddressSpaceSize;
        internal uint MaxBoundDescriptorSets;
        internal uint MaxPerStageDescriptorSamplers;
        internal uint MaxPerStageDescriptorUniformBuffers;
        internal uint MaxPerStageDescriptorStorageBuffers;
        internal uint MaxPerStageDescriptorSampledImages;
        internal uint MaxPerStageDescriptorStorageImages;
        internal uint MaxPerStageDescriptorInputAttachments;
        internal uint MaxPerStageResources;
        internal uint MaxDescriptorSetSamplers;
        internal uint MaxDescriptorSetUniformBuffers;
        internal uint MaxDescriptorSetUniformBuffersDynamic;
        internal uint MaxDescriptorSetStorageBuffers;
        internal uint MaxDescriptorSetStorageBuffersDynamic;
        internal uint MaxDescriptorSetSampledImages;
        internal uint MaxDescriptorSetStorageImages;
        internal uint MaxDescriptorSetInputAttachments;
        internal uint MaxVertexInputAttributes;
        internal uint MaxVertexInputBindings;
        internal uint MaxVertexInputAttributeOffset;
        internal uint MaxVertexInputBindingStride;
        internal uint MaxVertexOutputComponents;
        internal uint MaxTessellationGenerationLevel;
        internal uint MaxTessellationPatchSize;
        internal uint MaxTessellationControlPerVertexInputComponents;
        internal uint MaxTessellationControlPerVertexOutputComponents;
        internal uint MaxTessellationControlPerPatchOutputComponents;
        internal uint MaxTessellationControlTotalOutputComponents;
        internal uint MaxTessellationEvaluationInputComponents;
        internal uint MaxTessellationEvaluationOutputComponents;
        internal uint MaxGeometryShaderInvocations;
        internal uint MaxGeometryInputComponents;
        internal uint MaxGeometryOutputComponents;
        internal uint MaxGeometryOutputVertices;
        internal uint MaxGeometryTotalOutputComponents;
        internal uint MaxFragmentInputComponents;
        internal uint MaxFragmentOutputAttachments;
        internal uint MaxFragmentDualSrcAttachments;
        internal uint MaxFragmentCombinedOutputResources;
        internal uint MaxComputeSharedMemorySize;
        internal unsafe fixed uint [3];
        internal uint MaxComputeWorkGroupInvocations;
        internal unsafe fixed uint [3];
        internal uint SubPixelPrecisionBits;
        internal uint SubTexelPrecisionBits;
        internal uint MipmapPrecisionBits;
        internal uint MaxDrawIndexedIndexValue;
        internal uint MaxDrawIndirectCount;
        internal float MaxSamplerLodBias;
        internal float MaxSamplerAnisotropy;
        internal uint MaxViewports;
        internal unsafe fixed uint [2];
        internal unsafe fixed float [2];
        internal uint ViewportSubPixelBits;
        internal UIntPtr MinMemoryMapAlignment;
        internal ulong MinTexelBufferOffsetAlignment;
        internal ulong MinUniformBufferOffsetAlignment;
        internal ulong MinStorageBufferOffsetAlignment;
        internal int MinTexelOffset;
        internal uint MaxTexelOffset;
        internal int MinTexelGatherOffset;
        internal uint MaxTexelGatherOffset;
        internal float MinInterpolationOffset;
        internal float MaxInterpolationOffset;
        internal uint SubPixelInterpolationOffsetBits;
        internal uint MaxFramebufferWidth;
        internal uint MaxFramebufferHeight;
        internal uint MaxFramebufferLayers;
        internal SampleCountFlags FramebufferColorSampleCounts;
        internal SampleCountFlags FramebufferDepthSampleCounts;
        internal SampleCountFlags FramebufferStencilSampleCounts;
        internal SampleCountFlags FramebufferNoAttachmentsSampleCounts;
        internal uint MaxColorAttachments;
        internal SampleCountFlags SampledImageColorSampleCounts;
        internal SampleCountFlags SampledImageIntegerSampleCounts;
        internal SampleCountFlags SampledImageDepthSampleCounts;
        internal SampleCountFlags SampledImageStencilSampleCounts;
        internal SampleCountFlags StorageImageSampleCounts;
        internal uint MaxSampleMaskWords;
        internal uint TimestampComputeAndGraphics;
        internal float TimestampPeriod;
        internal uint MaxClipDistances;
        internal uint MaxCullDistances;
        internal uint MaxCombinedClipAndCullDistances;
        internal uint DiscreteQueuePriorities;
        internal unsafe fixed float [2];
        internal unsafe fixed float [2];
        internal float PointSizeGranularity;
        internal float LineWidthGranularity;
        internal uint StrictLines;
        internal uint StandardSampleLocations;
        internal ulong OptimalBufferCopyOffsetAlignment;
        internal ulong OptimalBufferCopyRowPitchAlignment;
        internal ulong NonCoherentAtomSize;
    }
}