using System;

namespace SixtenLabs.SpawnOfVulkan
{
    unsafe internal struct PhysicalDeviceLimits
    {
        internal uint maxImageDimension1D;
        internal uint maxImageDimension2D;
        internal uint maxImageDimension3D;
        internal uint maxImageDimensionCube;
        internal uint maxImageArrayLayers;
        internal uint maxTexelBufferElements;
        internal uint maxUniformBufferRange;
        internal uint maxStorageBufferRange;
        internal uint maxPushConstantsSize;
        internal uint maxMemoryAllocationCount;
        internal uint maxSamplerAllocationCount;
        internal ulong bufferImageGranularity;
        internal ulong sparseAddressSpaceSize;
        internal uint maxBoundDescriptorSets;
        internal uint maxPerStageDescriptorSamplers;
        internal uint maxPerStageDescriptorUniformBuffers;
        internal uint maxPerStageDescriptorStorageBuffers;
        internal uint maxPerStageDescriptorSampledImages;
        internal uint maxPerStageDescriptorStorageImages;
        internal uint maxPerStageDescriptorInputAttachments;
        internal uint maxPerStageResources;
        internal uint maxDescriptorSetSamplers;
        internal uint maxDescriptorSetUniformBuffers;
        internal uint maxDescriptorSetUniformBuffersDynamic;
        internal uint maxDescriptorSetStorageBuffers;
        internal uint maxDescriptorSetStorageBuffersDynamic;
        internal uint maxDescriptorSetSampledImages;
        internal uint maxDescriptorSetStorageImages;
        internal uint maxDescriptorSetInputAttachments;
        internal uint maxVertexInputAttributes;
        internal uint maxVertexInputBindings;
        internal uint maxVertexInputAttributeOffset;
        internal uint maxVertexInputBindingStride;
        internal uint maxVertexOutputComponents;
        internal uint maxTessellationGenerationLevel;
        internal uint maxTessellationPatchSize;
        internal uint maxTessellationControlPerVertexInputComponents;
        internal uint maxTessellationControlPerVertexOutputComponents;
        internal uint maxTessellationControlPerPatchOutputComponents;
        internal uint maxTessellationControlTotalOutputComponents;
        internal uint maxTessellationEvaluationInputComponents;
        internal uint maxTessellationEvaluationOutputComponents;
        internal uint maxGeometryShaderInvocations;
        internal uint maxGeometryInputComponents;
        internal uint maxGeometryOutputComponents;
        internal uint maxGeometryOutputVertices;
        internal uint maxGeometryTotalOutputComponents;
        internal uint maxFragmentInputComponents;
        internal uint maxFragmentOutputAttachments;
        internal uint maxFragmentDualSrcAttachments;
        internal uint maxFragmentCombinedOutputResources;
        internal uint maxComputeSharedMemorySize;
        internal unsafe fixed uint maxComputeWorkGroupCount[3];
        internal uint maxComputeWorkGroupInvocations;
        internal unsafe fixed uint maxComputeWorkGroupSize[3];
        internal uint subPixelPrecisionBits;
        internal uint subTexelPrecisionBits;
        internal uint mipmapPrecisionBits;
        internal uint maxDrawIndexedIndexValue;
        internal uint maxDrawIndirectCount;
        internal float maxSamplerLodBias;
        internal float maxSamplerAnisotropy;
        internal uint maxViewports;
        internal unsafe fixed uint maxViewportDimensions[2];
        internal unsafe fixed float viewportBoundsRange[2];
        internal uint viewportSubPixelBits;
        internal UIntPtr minMemoryMapAlignment;
        internal ulong minTexelBufferOffsetAlignment;
        internal ulong minUniformBufferOffsetAlignment;
        internal ulong minStorageBufferOffsetAlignment;
        internal int minTexelOffset;
        internal uint maxTexelOffset;
        internal int minTexelGatherOffset;
        internal uint maxTexelGatherOffset;
        internal float minInterpolationOffset;
        internal float maxInterpolationOffset;
        internal uint subPixelInterpolationOffsetBits;
        internal uint maxFramebufferWidth;
        internal uint maxFramebufferHeight;
        internal uint maxFramebufferLayers;
        internal SampleCountFlags framebufferColorSampleCounts;
        internal SampleCountFlags framebufferDepthSampleCounts;
        internal SampleCountFlags framebufferStencilSampleCounts;
        internal SampleCountFlags framebufferNoAttachmentsSampleCounts;
        internal uint maxColorAttachments;
        internal SampleCountFlags sampledImageColorSampleCounts;
        internal SampleCountFlags sampledImageIntegerSampleCounts;
        internal SampleCountFlags sampledImageDepthSampleCounts;
        internal SampleCountFlags sampledImageStencilSampleCounts;
        internal SampleCountFlags storageImageSampleCounts;
        internal uint maxSampleMaskWords;
        internal uint timestampComputeAndGraphics;
        internal float timestampPeriod;
        internal uint maxClipDistances;
        internal uint maxCullDistances;
        internal uint maxCombinedClipAndCullDistances;
        internal uint discreteQueuePriorities;
        internal unsafe fixed float pointSizeRange[2];
        internal unsafe fixed float lineWidthRange[2];
        internal float pointSizeGranularity;
        internal float lineWidthGranularity;
        internal uint strictLines;
        internal uint standardSampleLocations;
        internal ulong optimalBufferCopyOffsetAlignment;
        internal ulong optimalBufferCopyRowPitchAlignment;
        internal ulong nonCoherentAtomSize;
    }
}